version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0801"
      POSTGRES_DB: dockerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web-app:
    image: spring-boot-docker:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
